/**
 * telegram-userbot.js — MTProto listener for Telegram signal channels.
 * Monitors @agentmeridian + private group, writes signals to signals/inbox/.
 *
 * Requires (in .env):
 *   TELEGRAM_API_ID      — from my.telegram.org
 *   TELEGRAM_API_HASH    — from my.telegram.org
 *   TELEGRAM_SESSION     — generated by: node scripts/telegram-auth.js
 *   TELEGRAM_WATCH_IDS   — comma-separated numeric chat IDs (set by auth script)
 *
 * Run: node telegram-userbot.js
 * Via systemd: meridian-telegram-userbot.service
 */
import { TelegramClient } from "telegram";
import { StringSession } from "telegram/sessions/index.js";
import { NewMessage } from "telegram/events/index.js";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import "dotenv/config";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const INBOX_DIR = path.join(__dirname, "signals", "inbox");

const API_ID   = parseInt(process.env.TELEGRAM_API_ID, 10);
const API_HASH = process.env.TELEGRAM_API_HASH;
const SESSION  = process.env.TELEGRAM_SESSION || "";

// Numeric chat IDs from TELEGRAM_WATCH_IDS + the @agentmeridian username (resolved at start)
const EXTRA_IDS = (process.env.TELEGRAM_WATCH_IDS || "")
  .split(",").map((s) => s.trim()).filter(Boolean);

const PUBLIC_USERNAMES = ["agentmeridian"];

const SOL_ADDR_RE = /\b[1-9A-HJ-NP-Za-km-z]{32,44}\b/g;

function isLikelySolanaAddress(str) {
  if (str.length < 32 || str.length > 44) return false;
  if (!/\d/.test(str)) return false;
  return true;
}

function writeInbox(text, chatId) {
  fs.mkdirSync(INBOX_DIR, { recursive: true });
  const filename = `${Date.now()}-tg-${chatId}.txt`;
  fs.writeFileSync(path.join(INBOX_DIR, filename), text, "utf8");
  console.log(`[inbox] ${filename}`);
}

async function main() {
  if (!API_ID || !API_HASH) {
    console.error("[tg] TELEGRAM_API_ID / TELEGRAM_API_HASH not set in .env");
    process.exit(1);
  }
  if (!SESSION) {
    console.error("[tg] TELEGRAM_SESSION not set — run: node scripts/telegram-auth.js first");
    process.exit(1);
  }

  const client = new TelegramClient(new StringSession(SESSION), API_ID, API_HASH, {
    connectionRetries: 5,
    retryDelay: 3000,
  });

  await client.connect();
  const me = await client.getMe();
  console.log(`[tg-userbot] Connected as @${me.username || me.phone}`);

  // Resolve public channel usernames to numeric IDs
  const watchIds = new Set(EXTRA_IDS);
  for (const username of PUBLIC_USERNAMES) {
    try {
      const entity = await client.getEntity(username);
      watchIds.add(entity.id.toString());
      console.log(`[tg-userbot] Watching @${username} → id=${entity.id}`);
    } catch (e) {
      console.warn(`[tg-userbot] Cannot resolve @${username}: ${e.message}`);
    }
  }

  if (watchIds.size === 0) {
    console.warn("[tg-userbot] No chats to watch — check TELEGRAM_WATCH_IDS and @agentmeridian");
  } else {
    console.log(`[tg-userbot] Watching ${watchIds.size} chat(s): ${[...watchIds].join(", ")}`);
  }

  client.addEventHandler((event) => {
    const msg = event.message;
    if (!msg?.message) return;

    // Extract numeric chat ID from peerId
    const peerId  = msg.peerId;
    const chatId  = (peerId?.channelId ?? peerId?.chatId ?? peerId?.userId)?.toString();
    if (!chatId || (watchIds.size > 0 && !watchIds.has(chatId))) return;

    const text    = msg.message;
    const addrs   = [...new Set(
      [...text.matchAll(SOL_ADDR_RE)].map((m) => m[0]).filter(isLikelySolanaAddress)
    )];

    if (addrs.length === 0) return;

    console.log(`[tg] Signal from chat ${chatId}: ${addrs.join(", ")}`);
    console.log(`     ${text.slice(0, 140)}`);
    writeInbox(text, chatId);
  }, new NewMessage({}));

  console.log("[tg-userbot] Listening for messages...");
  await new Promise(() => {}); // keep alive until process killed
}

main().catch((e) => {
  console.error("[tg-userbot fatal]", e.message || e);
  process.exit(1);
});
